# Generated by Django 3.0.5 on 2020-05-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileadmin', '0002_auto_20200509_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
