# Generated by Django 3.0.5 on 2020-06-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileadmin', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
